In [1]:
import numpy as np

In [17]:
arr = np.array([[1,2,3,4],[10,20,30,40],[5,6,7,8]])
print (arr)
print (type(arr))
print (arr.ndim) # return the dimention

[[ 1  2  3  4]
 [10 20 30 40]
 [ 5  6  7  8]]
<class 'numpy.ndarray'>
2


In [27]:
#indexing
print (arr[0]) 
print(arr[0]+arr[2])
print (arr[0,3]) #access element by raw and column



[1 2 3 4]
[ 6  8 10 12]
4


In [57]:
#sclicing
print (arr[1:3]) 
print("------------------------------")
print (arr[0:])
print("------------------------------")
print (arr[-3:-1]) #exclude last element
print("------------------------------")
print(arr[1, 1:3]) #sclicing 2D array
print("------------------------------")

print(arr[0:2, 1:4])

print ("                                         ")
print ("((((((((((1DAray))))))))))")
a=np.array([1,2,3,4,5,6])
print (a[0:7:2]) #slicing by steps
print("------------------------------")
print(a[::3]) #sclicing entire array by steps 


[[10 20 30 40]
 [ 5  6  7  8]]
------------------------------
[[ 1  2  3  4]
 [10 20 30 40]
 [ 5  6  7  8]]
------------------------------
[[ 1  2  3  4]
 [10 20 30 40]]
------------------------------
[20 30]
------------------------------
[[ 2  3  4]
 [20 30 40]]
                                         
((((((((((1DAray))))))))))
[1 3 5]
------------------------------
[1 4]


In [58]:
print(arr.dtype)#datatype of array

int32


In [59]:
#copy vs veiw
x = a.copy()
y=a.view()
print (a)
print (x)
print (y)
a[0]=100
print (a)
print (x) # The copy SHOULD NOT be affected by the changes made to the original array.
print (y) # The view SHOULD be affected by the changes made to the original array.
print(x.base) #copy returns none
print(y.base)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
None
[100   2   3   4   5   6]


In [60]:
#shape
print('shape of array :', arr.shape)

shape of array : (3, 4)


In [68]:
#reshape
newarr = a.reshape(3, 2) #reshape without missing data 
newarr
newarr = arr.reshape(-1) #return the array into 1D (flatten)
newarr

array([ 1,  2,  3,  4, 10, 20, 30, 40,  5,  6,  7,  8])

In [70]:
#iterating on array
for x in np.nditer(arr): #by using nditer function instead of making nested loops
     print(x+3)

4
5
6
7
13
23
33
43
8
9
10
11


In [71]:
#iterating on np array
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 10
(1, 1) 20
(1, 2) 30
(1, 3) 40
(2, 0) 5
(2, 1) 6
(2, 2) 7
(2, 3) 8


In [97]:
#array join
a1=np.array([1,2,3,4,5])
a2=np.array([10,11,12,13,14])

np.concatenate((a1, a2)) #1) by using concatenate
np.stack ((a1,a2))  #2) by using stack
np.hstack((a1, a2)) #3) by using horizontal stack (concat horizontally) 
np.vstack((a1, a2)) #4) by using vertical stack (concat vertically)
np.dstack((a1, a2)) #5) by using height stack (concat along height)

array([[[ 1, 10],
        [ 2, 11],
        [ 3, 12],
        [ 4, 13],
        [ 5, 14]]])

In [112]:
# array slite
ary=np.array([1,2,3,4,5,6])
np.array_split(ary,2)
ary2=np.array([[1,2,3],[4,5,6]])
np.array_split(ary2,2)
np.hsplit(ary2, 3)


[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [118]:
#search
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=np.where(arr%2==0) #print index
arr1

(array([1, 3, 5, 7, 9], dtype=int64),)

In [120]:
#sort
t=np.array([7,5,0,2,9,57])
np.sort(t)

array([ 0,  2,  5,  7,  9, 57])

In [128]:
#filter
arr=np.array([1,2,3,4,5,6,7,8,9,10])
filtered=arr%2==0
newarr=arr[filtered]
print (filtered)
print (newarr)

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [175]:
#random
from numpy import random
x = random.rand() #rand return float bet 0,1
x = random.randint(100, size=(5)) #The randint() method takes a size parameter where you can specify the shape of an array
random.rand(5) #craete random array from 5 items bet 0,1

#-----------------------------------------------------------------

random.shuffle(arr) #The shuffle() method makes changes to the original array.
arr
print(random.permutation(arr)) #The permutation() method returns a re-arranged array (and leaves the original array un-changed).
arr
np.random.randint(1, 100, 10) #take lower and heighr range 

[6 7 5 9 8 1 3 2 4]


array([ 4, 38,  4,  5, 46, 37, 96, 50, 87, 80])

In [176]:
# arthemetic
arr1= np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])
#newarr = np.add(arr1, arr2)
newarr = np.subtract(arr1, arr2)
newarr = np.multiply(arr1, arr2)
newarr = np.divide(arr2, arr1)
newarr = np.power(arr1, arr2)
newarr = np.mod(arr2, arr1) # %
newarr = np.remainder(arr1, arr2)
newarr = np.divmod(arr1, arr2)
newarr = np.absolute(arr)
newarr= np.sqrt(arr)
newarr

array([1.        , 1.41421356, 3.        , 2.44948974, 1.73205081,
       2.23606798, 2.        , 2.64575131, 2.82842712])

In [168]:
# rounding
np.trunc([-3.1666, 3.6667])#remove float part
np.fix([-3.1666, 3.6667])# remove float part
np.around(3.1666, 2) #round up by decimal place
np.floor([-3.1666, 3.6667]) #round down
np.ceil([-3.1666, 3.6667]) #round up

array([-3.,  4.])

In [173]:
#log
print(np.log10(arr)) #log of base 10
print(np.log(arr)) #base e


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
